---
# tasks file for ansible-role-globus

- name: Make the software directory
  file: path="{{ software_path }}" state=directory mode=0777

- name: Install the globus-cli
  import_tasks: install_cli.yml
  when: "{{install_cli}}"

- name: Configure the endpoint
  import_tasks: configure_endpoint.yml
  when: "{{configure_endpoint}}"

- name: Transfer files
  import_tasks: transfer_files.yml
  when: "{{transfer_files}}"
